services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx-container
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/project
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - pg
    networks:
      - rick_morty
  php:
    build:
      context: .
      dockerfile: ./docker/php/Dockerfile
    container_name: php-container
    ports:
      - "9000:9000"
    volumes:
      - ./:/var/www/project
    networks:
      - rick_morty

  pg:
    image: postgres:17.5
    container_name: pg_container
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5430:5432"
    volumes:
      - pg_rick_morty:/var/lib/postgresql/data/pgdata
    networks:
      - rick_morty

networks:
  rick_morty:

volumes:
  pg_rick_morty: